DROP TABLE IF EXISTS stub;
CREATE TABLE stub (
	stub_id INTEGER PRIMARY KEY,
	stub_name TEXT NOT NULL,
	stub_description TEXT NOT NULL,
	stub_created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
	stub_updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);